package id

// Identity is the external caller identity (Gate 1 result).
// Internal actor↔actor calls leave Identity zero (IsZero == true).
// Generated by transport server at handshake and attached to every Frame
// from that connection.
type Identity struct {
	Kind    IdentityKind
	Subject string
	Role    Role // caller role, used by PolicyStore evaluation
}

// IsZero reports whether this is the anonymous, role-less identity.
func (i Identity) IsZero() bool {
	return i.Kind == IdentityAnonymous && i.Subject == "" && i.Role == ""
}

// IdentityKind discriminates how the identity was established.
type IdentityKind int

const (
	// IdentityAnonymous is the unauthenticated identity.
	// Only callables with an explicit anonymous-allowing Policy are reachable.
	IdentityAnonymous IdentityKind = iota
	// IdentityToken is a Bearer-token-authenticated identity.
	IdentityToken
	// IdentityAppCertificate is a cross-App mTLS / certificate identity.
	IdentityAppCertificate
)

// String returns the canonical wire-format spelling of k —
// "anonymous" / "token" / "app_certificate".
func (k IdentityKind) String() string {
	switch k {
	case IdentityAnonymous:
		return "anonymous"
	case IdentityToken:
		return "token"
	case IdentityAppCertificate:
		return "app_certificate"
	}
	return ""
}
